### ISSUE TITLE
Half-Life 2 Vehicles Have a Shrunken Invisible Gizmo

### ISSUE THREAD

**Issue by Zedimation** [penolakushari/RagdollMover#2]
Any vehicle that uses Half-Life 2 functions gets a small, invisible, yet functional gizmo. However, their prop variants, and vehicles using Simfphys, works per normal. Though any bone using physics continues movement even if told otherwise such as the tires; labelling as a non-issue for now.

**Comment by penolakushari** [comment]
Yeah, HL2 vehicle entities are quite a messy thing, although I didn't look at how they work at all. Feature to disable entity filter was meant to work with specific entities like cameras, lights and stuff, and since every custom entity like that uses its own class, setting up filter to include them would be a mess. Plus if someone makes a new camera tool, it'd be outside of the filter, so people won't be able to manipulate those.

**Comment by penolakushari** [comment]
HL2's jeep physics prop seems to be just weird overall - for some reason its physics object links to bone -1. I've got no idea what is that.

**Comment by penolakushari** [comment]
Ah, that is the general bone that physics props work with, essentially their "root" bone. Whole problem arises from the fact that jeep's root is underground, and GetPos doesn't work if bone or anything is outside the map.

**Comment by penolakushari** [comment]
92404b3 This issue should be partially solved now, as with these changes it is possible to move ragdoll mover gizmo back inside of the map so it could be used.
